import Head from "next/head";

export default function Layout({ children }: React.PropsWithChildren<{}>) {
  return (
    <div>
      <Head>
        <title>Covid testing times app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </div>
  );
}
